### ISSUE TITLE
Copy gif URL to clipboard

### ISSUE THREAD

**Issue by shatgupt** [mr-pennyworth/alfred-gif#1]
First of all, thanks a lot for making this! I have been looking for an Alfred workflow that shows gif previews for so long! This solves it very nicely.

I had a feature request to make to allow for copying the gif URL to clipboard as my chat application displays gif properly only when fetched from a URL. Would it be possible to do that with a modifier, say Option + Click? I would gladly send a PR but I don't really know Swift yet to make the required the changes (I am new to macOS as well).

Thanks again for making this!

**Comment by mr-pennyworth** [comment]
Didn't have a need for this because all my chat apps accept direct images...
For the kind of chat apps that you describe, this seems like a legit use case.

I've implemented "⌥ for url" in the latest release.
