### ISSUE TITLE
Feature Request: Use Giphy

### ISSUE THREAD

**Issue by billyromano** [mr-pennyworth/alfred-gif#4]
Would it be possible to setup the workflow to have the option of using Giphy or Tenor?

I'd be happy to help work on it, but I don't understand the development workflow. Swift seems pretty easy to understand and develop with, but I don't know how to build that portion of the project.

**Comment by mr-pennyworth** [comment]
It would be possible. If you don't care about having an option to choose, and want just Giphy (for your own version), that would be even easier. Take a look at this: https://github.com/mr-pennyworth/alfred-gif/blob/main/gif-downloader/gif-downloader.js#L199 that's the only file that would need a change. I have a suspicion that swift part of the project won't need to be changed...

About building the workflow, take a look at the build scripts (https://github.com/mr-pennyworth/alfred-gif/tree/main/build-scripts) and how those build scripts are used by github to automatically build the workfolw (https://github.com/mr-pennyworth/alfred-gif/blob/main/.github/workflows/build.yml)

By the way, main reason for choosing Tenor was google has their own servers to serve Tenor GIFs and those are much faster than both Tenor's original version and Giphy.

**Comment by billyromano** [comment]
I'll work on a separate Giphy version and I was already messing with the gif-downloader.js code and started setting up the Giphy API connection.

The GitHub build process is new to me. I'm familiar with Bitbucket pipelines which is similar, so I'll do some research into the GitHub setup. I understand the bash scripts now and I should be able to build it locally for testing.

Just curious, what code editor do you use for this project? I normally use Webstorm and I haven't worked on any Swift projects yet.

**Comment by mr-pennyworth** [comment]
> Just curious, what code editor do you use for this project? I normally use Webstorm and I haven't worked on any Swift projects yet.

I use AppCode (https://blog.jetbrains.com/objc/) for swift.
I've heard Xcode is better, but lack of vim keybindings is a deal breaker for me, so I don't use it.

**Comment by mr-pennyworth** [comment]
@billyromano I see you've integrated giphy in your fork :)
In case you're interested in using both simultaneously, take a look at the latest release, it supports both services and stickers from both. Also, it is noticeably faster now!
