### ISSUE TITLE
Unable to view on M1 MacBook Pro

### ISSUE THREAD

**Issue by JakeStevenson** [mr-pennyworth/alfred-gif#6]
It appears to download a list of gifs, but the window displaying results never shows.

These errors appear in the console:
`
2021-05-28 15:23:42.790197-0500 AlfredGifBrowser[21138:4704770] [ScriptFilterServer.swift:34 respond(with:)] Responded to alfred: ScriptFilterResponse(items: [Alfred.ScriptFilterResponse.Item(arg: "dummy", uid: nil, title: "Select with arrow keys, drag-n-drop with mouse", subtitle: Optional("[↩: search again] [⌘: copy GIF] [⌥: copy URL]"), valid: nil, match: nil, autocomplete: nil, quicklookurl: nil, type: nil, text: nil, icon: nil, mods: nil)])
2021-05-28 15:23:55.640738-0500 AlfredGifBrowser[21138:4704770] Metal API Validation Enabled
2021-05-28 15:23:55.683921-0500 AlfredGifBrowser[21138:4704770] fopen failed for data file: errno = 2 (No such file or directory)
2021-05-28 15:23:55.683950-0500 AlfredGifBrowser[21138:4704770] Errors found! Invalidating cache...
2021-05-28 15:23:55.740299-0500 AlfredGifBrowser[21138:4704770] +[MTLIOAccelDevice registerDevices]: Zero Metal services found
`

I'm still trying to learn my way around Swift and Xcode, so I'm dropping breakpoints into a few places and trying to examine the values, but I'm still struggling to figure them out.  If there is a specific value you would like me to examine I'd be happy to.

**Comment by JakeStevenson** [comment]
Throwing some log statements around it looks like alfredFrame is never being actually given a the size and shape it should use.  I hard coded some values in on it's initialization and the window did appear at that hardcoded location.

**Comment by mr-pennyworth** [comment]
Thanks @JakeStevenson!!

This was crucial piece of information.
My hypothesis: the workflow should start working all right if you restart Alfred.

```
killall Alfred
```

should do the trick.

Also, I've modified the workflow such that this is clearly communicated to the user during the install process. Please go ahead and reopen the issue if that still doesn't work!

**Comment by JakeStevenson** [comment]
No, I've restarted Alfred multiple times and it does not help.  

I'm still figuring the code out, but it looks like the rect used to size and place the browser only gets set when Alfred sends the notification for "selection.changed", right?  In my debugging I never get any notifications from "alfred.presssecretary". Is that because it is running in the debugger? 

I'm using Alfred 4.3.4.

**Comment by mr-pennyworth** [comment]
>  In my debugging I never get any notifications from "alfred.presssecretary". 

Yep, that's the problem!

> Is that because it is running in the debugger?

Hmm, interesting! I don't think the debugger changes anything...

Can you verify that the following command outputs `1`?
```
# should print 1
defaults read com.runningwithcrayons.Alfred experimental.presssecretary -bool
```

Also, here's another verification that you can do:

1. Kill Alfred
2. When you start Alfred again for the first time, you should see this notification: 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/74945464/120104557-9c70c200-c172-11eb-9f10-2b50f9d9f019.png">


> I'm using Alfred 4.3.4.

Any version newer than `4.3` has the Press Secretary, so the version is unlikely the problem.

**Comment by JakeStevenson** [comment]
Yes, I did turn on the experimental feature, that notification does pop up, and the command confirms it. 

I'll keep digging around, and if you have any other debugging ideas let me know.

**Comment by JakeStevenson** [comment]
Wait, now it works!  I hate not knowing exactly why, but it does.  Maybe I enabled presssecretary yesterday but didn't do the full killall of all the important items until now.

Thank you for the help.  Using this should be fun.
