### ISSUE TITLE
Can't use arrow key despite accessibility permission granted. Also drag and drop doesn't work for some gifs

### ISSUE THREAD

**Issue by billza7** [mr-pennyworth/alfred-gif#7]
I've tried removing and reinserting the "AlfredGifBrowser" in accessibility, restarting Alfred and still can't use arrow key to navigate the gif previews. So I've had to resort to Drag and Drop and, while it works for some GIFs, sometimes when you drag one GIF, the adjacent GIFs get dragged instead.

**Comment by mr-pennyworth** [comment]
Hmm, that's strange.

Does the issue with arrow keys persist after
1. multiple searches?
2. some time (say, 5 minutes) have passed since `AlfredGifBrowser` was first launched?

About the adjacent GIF being dragged, which GIF is highlighted? the one under mouse pointer, or the one that ends up being dragged? (a highlighted GIF tends to have a border around it and it more vivid while all other GIFs look faded/washed-out)

The reason for asking above questions is:
I have observed both of these behaviors happen when `AlfredGifBrowser` has just started. (It typically corresponds to first few searches after a reboot / fresh workflow install)

**Comment by billza7** [comment]
Good news, it seems to be working as intended now. I don't know if it's because I just recently restarted my computer or due to the wait like you said. However, when I first made the post I was tinkering with it for more than 10 minutes and the issue was still there.

Strangely enough, the exact GIF that I had a problem with still has the problem. I can't copy it, and when I highlight it and drag it out, the GIF below is dragged instead. Other than this GIF, everything else works now. 

In case you're curious, the problematic GIF appears when I search "bored cat" and it's this damn [pusheen cat](https://c.tenor.com/vTYizuJXs28AAAAM/bored-pusheen.gif).

**Comment by mr-pennyworth** [comment]
> Good news, it seems to be working as intended now. I don't know if it's because I just recently restarted my computer or due to the wait like you said. However, when I first made the post I was tinkering with it for more than 10 minutes and the issue was still there.

Yayy! 🎉

> Strangely enough, the exact GIF that I had a problem with still has the problem. I can't copy it, and when I highlight it and drag it out, the GIF below is dragged instead. Other than this GIF, everything else works now.

Whoa! I wonder what could be going on here! 🤔
Could you attach these two files here?
- `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/mr.pennyworth.gif/tenor-bored-cat.html.injected.html`
- `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/mr.pennyworth.gif/tenor-bored-cat.html`

My hypothesis is that maybe something went wrong in generating that HTML. I can check it against mine and see if that's the case.

Also, after uploading those files here, can you try the following?
- delete both of those
- again do `gif bored cat` (this should regenerate the HTML)
- see if the issue persists

> In case you're curious, the problematic GIF appears when I search "bored cat" and it's this damn pusheen cat.

🤣🤣

**Comment by billza7** [comment]
Seems Github doesn't allow uploading of html files so here's a [DropOver link](https://dropover.cloud/a8f194). I've deleted the 2 files, retried, but the issue still persists. In the link I've also attached the recording.

**Comment by mr-pennyworth** [comment]
Thanks for the files and video! 😇

Wow that's a real head-scratcher! I tried the HTML files and they work fine on my setup. Given that this seems to be a one-off weird bug, I'm closing it for now with the intention to come back later when I'm feeling like chasing [heisenbugs](https://en.wikipedia.org/wiki/Heisenbug) or if this becomes a more common and frequent thing.

In case this needs to be debugged in future and dropover link goes away:
[Tenor Bored Cat.zip](https://github.com/mr-pennyworth/alfred-gif/files/6656190/Tenor.Bored.Cat.zip)

https://user-images.githubusercontent.com/74945464/122067442-342c0c80-ce11-11eb-96e4-6087133da429.mp4
